name: Annotate Tag

on:
  workflow_dispatch:
    inputs:
      tagName:
        description: 'Tag to annotate (e.g., mcp-v2.0.0)'
        required: true
      version:
        description: 'Version for notes (defaults to tagName without prefix mcp-v)'
        required: false

permissions:
  contents: write

jobs:
  annotate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Generate notes
        id: gen
        env:
          TAG: ${{ inputs.tagName }}
          VERSION_IN: ${{ inputs.version }}
        run: |
          set -euo pipefail
          TAG="${TAG}"
          VER="${VERSION_IN:-}"
          if [ -z "${VER}" ]; then
            # 自动检测版本号格式
            if [[ "$TAG" =~ ^mcp-v(.+)$ ]]; then
              VER="${BASH_REMATCH[1]}"
            elif [[ "$TAG" =~ ^v(.+)$ ]]; then
              VER="${BASH_REMATCH[1]}"
            else
              VER="$TAG"
            fi
          fi
          echo "version=${VER}" >> "$GITHUB_OUTPUT"

          # 尝试从CHANGELOG生成发布说明
          if node scripts/mcp-extract-changelog.mjs "${VER}" > .notes.tag 2>/dev/null; then
            echo "✅ Generated release notes from CHANGELOG"
          else
            echo "⚠️ No CHANGELOG entry found, using template"
            cat > .notes.tag << EOF
          # Release $TAG

          ## 🎯 Version Information
          - **Version**: $VER
          - **Release Date**: $(date +%Y-%m-%d)
          - **Tag**: $TAG

          ## 📦 Installation
          \`\`\`bash
          # Install MCP server
          npm install -g @starkdev020/codex-father-mcp-server@$VER

          # Or install main project
          npm install -g codex-father@$VER
          \`\`\`

          ## 🔗 Links
          - [GitHub Repository](https://github.com/yuanyuanyuan/codex-father)
          - [CHANGELOG](https://github.com/yuanyuanyuan/codex-father/blob/main/CHANGELOG.md)
          EOF
          fi

          echo "notes<<EOF" >> "$GITHUB_OUTPUT"
          cat .notes.tag >> "$GITHUB_OUTPUT"
          echo "EOF" >> "$GITHUB_OUTPUT"

      - name: Configure git user
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Annotate and push tag
        env:
          TAG: ${{ inputs.tagName }}
        run: |
          set -euo pipefail
          git fetch --tags --force
          git tag -fa "$TAG" -F .notes.tag
          git push origin :refs/tags/"$TAG" || true
          git push origin refs/tags/"$TAG" -f
