name: Release to GH Packages

on:
  push:
    branches:
      - main
    paths:
      - 'mcp/**'
      - '.releaserc'
      - '.github/workflows/release-ghpkgs.yml'
  workflow_dispatch: {}

permissions:
  contents: write
  packages: write

jobs:
  release-ghpkgs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Configure npm for GitHub Packages
        run: |
          echo "@yuanyuanyuan:registry=https://npm.pkg.github.com" >> ~/.npmrc
          echo "//npm.pkg.github.com/:_authToken=${GITHUB_TOKEN}" >> ~/.npmrc
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install dependencies (mcp package)
        working-directory: mcp/codex-mcp-server
        run: npm ci

      - name: Build (mcp package)
        working-directory: mcp/codex-mcp-server
        run: npm run build

      - name: Semantic Release (publish to GH Packages)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_CONFIG_REGISTRY: https://npm.pkg.github.com/
        run: npx -y semantic-release

