name: Release to GH Packages

on:
  # 仅在 PR 合并到 main 时触发（避免普通分支 push 消耗次数）
  pull_request:
    types: [closed]
    branches: [main]
    paths:
      - 'mcp/**'
      - '.releaserc'
      - '.github/workflows/release-ghpkgs.yml'
  # 仍保留手动触发
  workflow_dispatch: {}

permissions:
  contents: write
  packages: write

jobs:
  release-ghpkgs:
    runs-on: ubuntu-latest
    # 仅在 PR 已合并时执行；或手动触发
    if: github.event_name == 'workflow_dispatch' || (github.event_name == 'pull_request' && github.event.pull_request.merged == true)
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          # 在合并事件上检出合并提交；手动触发时默认 main
          ref: ${{ github.event_name == 'pull_request' && github.event.pull_request.merge_commit_sha || 'main' }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org/'

      - name: Configure npm for GitHub Packages
        run: |
          echo "@yuanyuanyuan:registry=https://npm.pkg.github.com" >> "$NPM_CONFIG_USERCONFIG"
          echo "//npm.pkg.github.com/:_authToken=${NODE_AUTH_TOKEN}" >> "$NPM_CONFIG_USERCONFIG"
          echo "always-auth=true" >> "$NPM_CONFIG_USERCONFIG"
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install dependencies (mcp package)
        working-directory: mcp/codex-mcp-server
        run: npm ci

      - name: Build (mcp package)
        working-directory: mcp/codex-mcp-server
        run: npm run build

      - name: Install semantic-release + plugins (no-save)
        run: |
          npm i --no-save \
            semantic-release \
            @semantic-release/commit-analyzer \
            @semantic-release/release-notes-generator \
            @semantic-release/changelog \
            @semantic-release/exec \
            @semantic-release/git \
            @semantic-release/github

      - name: Semantic Release (publish to GH Packages)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release
