name: Release to GH Packages

on:
  # 简化触发：仅 main 分支 push（通常来自 PR 合并）+ 手动触发
  push:
    branches: [main]
    paths:
      - 'mcp/**'
      - '.releaserc'
  workflow_dispatch: {}

permissions:
  contents: write
  packages: write

jobs:
  release-ghpkgs:
    concurrency:
      group: release-${{ github.ref }}
      cancel-in-progress: true
    runs-on: ubuntu-latest
    env:
      # 将可选的 NPM_TOKEN 暴露为 env，便于 if 判断
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org/'

      - name: Configure npm for GitHub Packages
        run: |
          echo "@yuanyuanyuan:registry=https://npm.pkg.github.com" >> "$NPM_CONFIG_USERCONFIG"
          echo "//npm.pkg.github.com/:_authToken=${NODE_AUTH_TOKEN}" >> "$NPM_CONFIG_USERCONFIG"
          echo "always-auth=true" >> "$NPM_CONFIG_USERCONFIG"
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure npm for npmjs (if NPM_TOKEN present)
        if: ${{ env.NPM_TOKEN != '' }}
        run: |
          echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" >> "$NPM_CONFIG_USERCONFIG"

      - name: Install dependencies (mcp package)
        working-directory: mcp/codex-mcp-server
        run: npm ci

      - name: Build (mcp package)
        working-directory: mcp/codex-mcp-server
        run: npm run build

      - name: Install semantic-release + plugins (no-save)
        run: |
          npm i --no-save \
            semantic-release \
            @semantic-release/commit-analyzer \
            @semantic-release/release-notes-generator \
            @semantic-release/changelog \
            @semantic-release/exec \
            @semantic-release/git \
            @semantic-release/github

      - name: Semantic Release (publish to GH Packages)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release
