name: Orchestrator Tests

on:
  push:
    branches: [ "feat/specs-006-docs-capability-assessment", "main", "release", "**/batch-*" ]
    paths:
      - 'core/orchestrator/**'
      - 'docs/schemas/stream-json-event.schema.json'
      - 'specs/006-docs-capability-assessment/contracts/events.md'
      - 'AGENTS.md'
      - 'package.json'
  pull_request:
    paths:
      - 'core/orchestrator/**'
      - 'docs/schemas/stream-json-event.schema.json'
      - 'specs/006-docs-capability-assessment/contracts/events.md'
      - 'AGENTS.md'
      - 'package.json'

jobs:
  orchestrator-tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version: ['18', '20']
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Run orchestrator tests (ORCHESTRATOR_TESTS=1)
        run: ORCHESTRATOR_TESTS=1 npm run test:orchestrator
